# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.HighVegCheckBox = QtWidgets.QCheckBox(self.frame)
        self.HighVegCheckBox.setObjectName("HighVegCheckBox")
        self.gridLayout_2.addWidget(self.HighVegCheckBox, 2, 0, 1, 1)
        self.medVegCheckBox = QtWidgets.QCheckBox(self.frame)
        self.medVegCheckBox.setObjectName("medVegCheckBox")
        self.gridLayout_2.addWidget(self.medVegCheckBox, 1, 0, 1, 1)
        self.lowVegCheckBox = QtWidgets.QCheckBox(self.frame)
        self.lowVegCheckBox.setObjectName("lowVegCheckBox")
        self.gridLayout_2.addWidget(self.lowVegCheckBox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.inputDirectoryBrowseButton = QtWidgets.QPushButton(self.frame_2)
        self.inputDirectoryBrowseButton.setObjectName("inputDirectoryBrowseButton")
        self.gridLayout_3.addWidget(self.inputDirectoryBrowseButton, 0, 2, 1, 1)
        self.inputDirectoryLabel = QtWidgets.QLabel(self.frame_2)
        self.inputDirectoryLabel.setObjectName("inputDirectoryLabel")
        self.gridLayout_3.addWidget(self.inputDirectoryLabel, 0, 0, 1, 1)
        self.inputDirectoryLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.inputDirectoryLineEdit.setObjectName("inputDirectoryLineEdit")
        self.gridLayout_3.addWidget(self.inputDirectoryLineEdit, 0, 1, 1, 1)
        self.recursiveSearchCheckbox = QtWidgets.QCheckBox(self.frame_2)
        self.recursiveSearchCheckbox.setObjectName("recursiveSearchCheckbox")
        self.gridLayout_3.addWidget(self.recursiveSearchCheckbox, 0, 3, 1, 1)
        self.outputDirectoryLabel = QtWidgets.QLabel(self.frame_2)
        self.outputDirectoryLabel.setObjectName("outputDirectoryLabel")
        self.gridLayout_3.addWidget(self.outputDirectoryLabel, 1, 0, 1, 1)
        self.outputDirectoryLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.outputDirectoryLineEdit.setObjectName("outputDirectoryLineEdit")
        self.gridLayout_3.addWidget(self.outputDirectoryLineEdit, 1, 1, 1, 1)
        self.outputDirectoryBrowseButton = QtWidgets.QPushButton(self.frame_2)
        self.outputDirectoryBrowseButton.setObjectName("outputDirectoryBrowseButton")
        self.gridLayout_3.addWidget(self.outputDirectoryBrowseButton, 1, 2, 1, 1)
        self.fanOutCheckBox = QtWidgets.QCheckBox(self.frame_2)
        self.fanOutCheckBox.setObjectName("fanOutCheckBox")
        self.gridLayout_3.addWidget(self.fanOutCheckBox, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.processButton = QtWidgets.QPushButton(self.centralwidget)
        self.processButton.setObjectName("processButton")
        self.gridLayout.addWidget(self.processButton, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chlorophyl"))
        self.HighVegCheckBox.setText(_translate("MainWindow", "High Vegetation"))
        self.medVegCheckBox.setText(_translate("MainWindow", "Medium Vegetation"))
        self.lowVegCheckBox.setText(_translate("MainWindow", "Low Vegetation"))
        self.inputDirectoryBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.inputDirectoryLabel.setText(_translate("MainWindow", "Input Directory:"))
        self.recursiveSearchCheckbox.setText(_translate("MainWindow", "Recursive"))
        self.outputDirectoryLabel.setText(_translate("MainWindow", "Output Directory:"))
        self.outputDirectoryBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.fanOutCheckBox.setText(_translate("MainWindow", "Fan out"))
        self.processButton.setText(_translate("MainWindow", "Process"))

